# pwatrip-twenty48-state-mysql Makefile

CAPABILITY_ID = "pwatrip:twenty48:state"
NAME = "pwatrip-twenty48-state-mysql"
VENDOR = "jhagmar"
PROJECT = pwatrip_twenty_48_state_mysql
VERSION = 0.1.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

